version: '3'

services:

  mongodb:

    image: mongo:latest

    container_name: dev-mongodb

    restart: on-failure

    volumes:

      - ./db_data_test:/data/db

    ports:

      - 27017:27017

    command: mongod

volumes:

  mongodb:

  mongodb_config: